service: subnet

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.stage}-${self:service}
  deploymentBucket:
    name: dataplattform-v2-deploymentbucket
  stackTags:
    Project: dataplattform
    Layer: infrastructure
  tags:
    Project: dataplattform
    Layer: infrastructure


resources:
  Resources:
    SubnetA:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: eu-central-1a
        CidrBlock: 10.192.50.0/24
        Tags:
          - Key: Name
            Value: SubnetA
        VpcId: !ImportValue ${self:custom.stage}-MainVPCID

    SubnetB:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: eu-central-1b
        CidrBlock: 10.192.51.0/24
        Tags:
          - Key: Name
            Value: SubnetB
        VpcId: !ImportValue ${self:custom.stage}-MainVPCID

    SubnetC:
      Type: AWS::EC2::Subnet
      Properties:
        AvailabilityZone: eu-central-1c
        CidrBlock: 10.192.52.0/24
        Tags:
          - Key: Name
            Value: SubnetC
        VpcId: !ImportValue ${self:custom.stage}-MainVPCID


  Outputs:
    SubnetNameA:
      Description: The subnet id
      Value: 
        Ref: SubnetA
      Export:
        Name: ${self:custom.stage}-SubnetAID

    SubnetNameB:
      Description: The subnet id
      Value: 
        Ref: SubnetB
      Export:
        Name: ${self:custom.stage}-SubnetBID

    SubnetNameC:
      Description: The subnet id
      Value: 
        Ref: SubnetC
      Export:
        Name: ${self:custom.stage}-SubnetCID