service: main-vpc

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: eu-central-1
  stackName: ${self:custom.stage}-${self:service}
  deploymentBucket:
    name: dataplattform-v2-deploymentbucket
  stackTags:
    Project: dataplattform
    Layer: infrastructure
  tags:
    Project: dataplattform
    Layer: infrastructure


resources:
  Resources:
    MainVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.192.0.0/16
        Tags:
          - Key: Name
            Value: MainVPC

  Outputs:
    MainVPCID:
      Description: The ID of the VPC
      Value: 
        Ref: MainVPC
      Export:
        Name: ${self:custom.stage}-MainVPCID